homalg-project/FinSetsForCAP

doc/Doc.autodoc, gap/FinSetsForCAP.gd, gap/FinSetsForCAP.gi, gap/SkeletalFinSetsForCAP.gd, gap/SkeletalFinSetsForCAP.gi
use new capabilities of CAP introduced in https://github.com/homalg-project/CAP_project/commit/591621324fb74e05d79821196adc48263d8cb0a7 and https://github.com/homalg-project/CAP_project/commit/b2d7785056f0196254e7ae9191dbb36561ecfc9a to improve the performance of computations which create many objects/morpisms
=> Performance tweaks

examples/doc/FinSet.g, examples/doc/FinSetNC.g, gap/FinSetsForCAP.gd, gap/FinSetsForCAP.gi
=> Change the notion of equality of finite sets

PackageInfo.g, examples/SeveralCats.g, gap/FinSetsForCAP.gi, gap/SkeletalFinSetsForCAP.gd, gap/SkeletalFinSetsForCAP.gi
This closes #30.
Moreover, it includes #31, so #31 should be merged first.
=> Provide constructors for SkeletalFinSets

PackageInfo.g, doc/Doc.autodoc, examples/IsHomSetInhabited.g, examples/SkeletalIsHomSetInhabited.g, gap/FinSetsForCAP.gi, gap/SkeletalFinSetsForCAP.gi
Only consider this PR after #35 has been merged.
=> Is hom set inhabited

make_dist.sh, release
Added release scripts.
I created the branch gh-pages and used these scripts to make the first release.
=> added release scripts

makefile, release-gap-package
If there is a PR 'Apply PackageJanitor to gh-pages', please merge both PRs together.
=> Apply PackageJanitor

PackageInfo.g, examples/SubobjectClassifier.g, gap/FinSetsForCAP.gi
renamed TruthMorphismIntoSubobjectClassifier -> TruthMorphismOfTrue
This PR is urgent.
=> Comply with Toposes v2021.11-03

PackageInfo.g, gap/FinSetsForCAP.gi
=> no need to AddTruthMorphismOfTrueWithGivenObjects anymore

PackageInfo.g, examples/PrecompileCategoryOfSkeletalFinSets.g, examples/PrecompileLinearAlgebraForCAP.g, examples/SkeletalCoastrictionToImage.g, gap/SkeletalFinSetsForCAP.gd, gap/SkeletalFinSetsForCAP.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi, makefile, process_coverage_ignored_lines.py, read.g, tst/testall_no_precompiled_code.g
This contains the main commit of https://github.com/homalg-project/FinSetsForCAP/pull/75 with some additional changes.
=> Precompile SkeletalFinSets

tst/CartesianClosedOpposite.tst
I will add the other test for SkeletalFinSets when the next GAP version is released.
I have also kept the sizes of the sets relatively small since otherwise testing might take forever on weaker machines (speaking of experience :D )
=> Test topos

PackageInfo.g, tst/SkeletalCartesianClosedOpposite.tst
Depends on https://github.com/homalg-project/Toposes/pull/55. I was only able to detect that bug in Toposes via this test. :)
And luckily, the skeletal test now also works without a new GAP.
=> Use topos test files

PackageInfo.g, examples/HeytingAlgebraOfSubobjects.g, examples/SkeletalHeytingAlgebraOfSubobjects.g
fixed typo in RelativePseudoComplementSubobject
=> comply with Toposes v2022.04-02

PackageInfo.g, examples/SkeletalCartesianLambdaIntroduction.g, examples/SkeletalCoastrictionToImage.g, examples/SkeletalCoequalizer.g, examples/SkeletalCoproduct.g, examples/SkeletalEqualizer.g, examples/SkeletalFiberProduct.g, examples/SkeletalHeytingAlgebraOfSubobjects.g, examples/SkeletalImageEmbedding.g, examples/SkeletalMonoEpi.g, examples/SkeletalPushout.g, gap/SkeletalFinSetsForCAP.gi
=> Disable logic of SkeletalFinSets

gap/SkeletalFinSetsForCAP.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi
=> simplified code ProjectionOntoCoequalizerWithGivenCoequalizer

PackageInfo.g, examples/HeytingAlgebraOfSubobjects.g, examples/InitialTerminal.g, examples/SubobjectClassifier.g, examples/notebooks/typed_lambda_calculus_and_category_theory.ipynb, gap/FinSetsForCAP.gi, gap/SkeletalFinSetsForCAP.gi
See commit messages for details.
=> Miscellaneous changes

PackageInfo.g, gap/SkeletalFinSetsForCAP.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi
suggest by @zickgraf in analogy to
https://github.com/homalg-project/CAP_project/pull/998
=> The typing information should always be obtained from the source and range

PackageInfo.g, doc/Doc.autodoc, examples/PrecompileCategoryOfSkeletalFinSets.g, examples/PushoutComplement.g, examples/SkeletalPushoutComplement.g, gap/CompilerLogic.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi
thanks Moussa Mbaye for working with me on the topos-theoretic implementation and @zickgraf for helping with the compilation
=> compiled PushoutComplement 🎉

ci_gaprc
despite re-initializing package info records
=> Make sure CapAndHomalg prefers packages in GAPInfo.UserGapRoot

PackageInfo.g, doc/Doc.autodoc, examples/SkeletalExactCoverWithGlobalElements.g, gap/CompilerLogic.gi, gap/SkeletalFinSetsForCAP.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi
=> AddExactCoverWithGlobalElements( SkeletalFinSets, ... )

.github/workflows/Tests.yml, dev/make_dist.sh, dev/release-gap-package
until the option --release-script is upstreamed
=> Include release-gap-package again temporarily

PackageInfo.g, gap/FinSetsForCAP.gi, gap/SkeletalFinSetsForCAP.gi
from PR https://github.com/homalg-project/CAP_project/pull/1240
=> comply with CartesianCategories v2023.02-04

PackageInfo.g, examples/SkeletalExactCoverWithGlobalElements.g, gap/SkeletalFinSetsForCAP.gi
and used it to simplify the corresponding Display method
=> installed PrintString for IsSkeletalFiniteSetMap

PackageInfo.g, gap/SkeletalFinSetsForCAP.gi, gap/precompiled_categories/CategoryOfSkeletalFinSetsPrecompiled.gi
and used it to "derive" MorphismsOfExternalHom
=> installed ExactCoverWithGlobalElements primitively

gap/SkeletalFinSets.gi
and FinSetOp/MapOfFinSets the "derived" ones
=> made AddObjectConstructor/AddMorphismConstructor the primitive operations

gap/SkeletalFinSets.gi
instead of FinSet/MapOfFinSets
=> use ObjectConstructor/MorphismConstructor

PackageInfo.g, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
where PreComposeList now takes source and range as arguments
=> comply with CAP v2023.08-16

PackageInfo.g, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
See https://github.com/homalg-project/CAP_project/pull/1464
=> Adjust to changes in CAP 2023.09-07

PackageInfo.g, examples/SkeletalColift.g, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
resolves https://github.com/homalg-project/FinSetsForCAP/issues/226
=> fixed IsColiftable

PackageInfo.g, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
See https://github.com/homalg-project/CAP_project/pull/1514
=> Adjust to CompilerForCAP commit 389bfebf83b5bd43b29b445cedefbb2eee4596a7

PackageInfo.g, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
See https://github.com/homalg-project/CAP_project/pull/1515
=> Adjust to CAP commit c4ff9952143a87c262556f82b55dd1471fa30e87

PackageInfo.g, gap/CompilerLogic.gi, gap/SkeletalFinSets.gi
See https://github.com/homalg-project/CAP_project/pull/1234
=> Adjust to CAP commit af2ea351d37afa90e9775773b689530d4047f123

PackageInfo.g, examples/SkeletalCartesianLambdaIntroduction.g, examples/SkeletalTopos.g, examples/Topos.g, gap/FinSets.gi, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi, tst/compare.tst
- Cartesian(Co)EvaluationMorphism -> CartesianLeft(Co)EvaluationMorphism
- *AdjunctionMap -> *LeftAdjunctionMap
=> comply with CartesianCategories v2024.01-05

PackageInfo.g, examples/PrecompileCategoryOfSkeletalFinSetsWithMorphismsGivenByLists.g, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
since it can be derived by generic algorithms in CartesianCategories
=> deleted AddCartesianBraidingInverseWithGivenDirectProducts

PackageInfo.g, gap/SkeletalFinSets.gi, gap/Tools.gd, gap/Tools.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
and used it to clarify CartesianLambdaElimination
=> d&i DigitInPositionalNotation

PackageInfo.g, gap/CompilerLogic.gi, gap/SkeletalFinSets.gi, gap/Tools.gd, gap/Tools.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
and used them to refactor AddProjectionInFactorOfDirectProductWithGivenDirectProduc
=> d&i RemIntWithDomain, QuoIntWithDomain, and DivIntWithGivenQuotient

PackageInfo.g, examples/SkeletalTopos.g, examples/Topos.g, gap/FinSets.gi, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
the purpose of this commit is to create the compiled code of AddCartesianRightEvaluationMorphismWithGivenSource for future comparison when the evaluation is derived from the adjunction
=> AddCartesianRight(Co)EvaluationMorphism

PackageInfo.g, examples/PrecompileCategoryOfSkeletalFinSetsWithMorphismsGivenByLists.g, gap/CompilerLogic.gi, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByListsPrecompiled.gi
and got rid of
* AddCartesianLambdaIntroduction
* AddCartesianRightEvaluationMorphismWithGivenSource (and improved its compiled code!)
=> added the right product-exponential adjunction

PackageInfo.g, gap/SkeletalFinSets.gi
which affects the derivation of the unitors and asccociators
=> added missing mathematical properties: SetIsStrictC(oc)artesianCategory

makefile
This reverts commit 1a720378603028ef2b7fa3fb06d74d85249986ac.
=> Revert "deactivate test-gap_to_julia"

PackageInfo.g, examples/SkeletalCartesianLambdaIntroduction.g, gap/CompilerLogic.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByLists_precompiled.gi
=> simplify compiled code of CartesianLambdaIntroduction

.github/workflows/Tests.yml, PackageInfo.g, dev/.release, dev/ci_gaprc, dev/release-gap-package, examples/precompile_CategoryOfSkeletalFinSetsWithMorphismsGivenByLists.g, tst/50_gap_old_formatting.tst
commit 222f357de5001b0e1c1ce60b8d1b7b45a1c4a32d
=> temporarily work around changes in GAP master

PackageInfo.g, gap/SkeletalFinSets.gi, gap/precompiled_categories/SkeletalCategoryOfFiniteSetsWithMorphismsGivenByLists_precompiled.gi
=> Adjust 'IsWellDefinedForObjects' and 'Equalizer' to make sure the datum of an object is a non-negative BigInt

PackageInfo.g, makefile
PR: https://github.com/homalg-project/FinSetsForCAP/pull/276
Bump version to V2025.08-04
=> Remove an experimental change in PR #276 that was not intended to be merged
